# Generated by Django 2.0.6 on 2019-06-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0005_cita_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
