# Generated by Django 2.0.6 on 2019-06-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0009_auto_20190622_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='categoria',
        ),
    ]
