# Generated by Django 2.0.6 on 2019-06-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0011_auto_20190622_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre_categoria'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
