# Generated by Django 2.0.6 on 2019-06-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0012_auto_20190623_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'solicitud', 'verbose_name_plural': 'solicitudes'},
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='solicitud_id',
            new_name='solicitud',
        ),
    ]
