# Generated by Django 2.0.6 on 2019-07-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0016_auto_20190715_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='descripcion_examen',
            field=models.CharField(default='No hay descripción', max_length=1000),
        ),
    ]
